### ISSUE TITLE
block of code for 'default' keyword won't run if 'switch' has an earlier 'return'(?)

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-review-conditionals#1]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/review-conditionals?module_item_id=396095

### Concern

in describing the **default** keyword for the **switch** statement, the text says (in bold!):
the only time it does not run is if the engine hits a break in one of the case statements.

But if the block runs **return**, then **default** will not run, right? So the phrase "the only time" seems extreme.

### Suggested Changes

Adapt this text for a switch block's earlier/potential use of 'return'?

**Comment by professor-ben** [comment]
Hi Brigham,

Thanks for your ticket. We've updated the language in the instructions to be a bit softer. While a `return` would exit the switch statement with the most recent value of the variable it's returning, there are a couple of points that we should consider:

1. `return` only works inside of a function, so it won't work in every `switch` statement
2. Because we're inside of a `switch` statement, it's best practice to only use keywords that apply to all `switch` statements whenever possible.

Since our block here isn't inside of a function, `return` would throw an error. The best approach if this were inside a function would be to exit the `switch` statement with a `break` and then return the final value of the variable outside of the `switch` statement.

Thanks!
Ben
